#!/usr/bin/env bash
# Writes Teleport role + bot + join token YAML to stdout.
# Usage: generate-teleport-resources.sh <join_method> <cluster_name> <namespace> <bot_name>
#   join_method: eks | gcp | aks | kubernetes
set -euo pipefail

JOIN_METHOD="${1:?join_method required}"
CLUSTER_NAME="${2:?cluster_name required}"
NAMESPACE="${3:?namespace required}"
BOT_NAME="${4:?bot_name required}"
# arg 5 usage depends on join method:
#   bound_keypair → the Ed25519 public key to embed in the token spec
#   token         → the pre-shared secret value (auto-generated by deploy.sh)
EXTRA_ARG="${5:-}"

TOKEN_NAME="tbot-${BOT_NAME}"

# ── Role + Bot (same for all join methods) ────────────────────────────────────
cat <<EOF
kind: role
version: v7
metadata:
  name: ${BOT_NAME}
spec:
  allow:
    rules:
      - resources: [event]
        verbs: [list, read]
---
kind: bot
version: v1
metadata:
  name: ${BOT_NAME}
spec:
  roles: [${BOT_NAME}]
---
EOF

# ── Join token (varies by method) ────────────────────────────────────────────
case "$JOIN_METHOD" in
  eks|gcp|aks)
    # Fetch both the issuer and JWKS via kubectl — no external curl needed,
    # so this works on private clusters (AKS, GKE private, EKS private endpoint).
    echo "Fetching OIDC config and JWKS for $JOIN_METHOD cluster..." >&2
    ISSUER=$(kubectl get --raw /.well-known/openid-configuration \
      | python3 -c "import sys,json; print(json.load(sys.stdin)['issuer'])")
    JWKS=$(kubectl get --raw /openid/v1/jwks)
    echo "OIDC issuer : $ISSUER" >&2
    echo "JWKS keys   : $(echo "$JWKS" | python3 -c "import sys,json; print(len(json.load(sys.stdin)['keys']))")" >&2

    # Escape JWKS for embedding in YAML
    JWKS_ESCAPED=$(printf '%s' "$JWKS" | python3 -c "import sys; print(sys.stdin.read().replace(\"'\", \"'\\\"'\\\"'\"))")

    cat <<EOF
kind: token
version: v2
metadata:
  name: ${TOKEN_NAME}
spec:
  roles: [Bot]
  join_method: kubernetes
  bot_name: ${BOT_NAME}
  kubernetes:
    type: static_jwks
    allow:
      - service_account: "${NAMESPACE}:tbot"
    static_jwks:
      jwks: '${JWKS_ESCAPED}'
EOF
    ;;

  kubernetes)
    # Self-hosted Teleport running in the same cluster — use in_cluster verification.
    cat <<EOF
kind: token
version: v2
metadata:
  name: ${TOKEN_NAME}
spec:
  roles: [Bot]
  join_method: kubernetes
  bot_name: ${BOT_NAME}
  kubernetes:
    type: in_cluster
    allow:
      - service_account: "${NAMESPACE}:tbot"
EOF
    ;;

  token)
    # The token value is auto-generated by deploy.sh and passed as arg 5.
    # metadata.name IS the token secret — tbot presents this string at join time.
    if [[ -z "$EXTRA_ARG" ]]; then
      echo "ERROR: token join method requires the token value as arg 5" >&2
      exit 1
    fi
    cat <<EOF
kind: token
version: v2
metadata:
  name: ${EXTRA_ARG}
spec:
  roles: [Bot]
  join_method: token
  bot_name: ${BOT_NAME}
EOF
    ;;

  bound_keypair)
    # The public key generated by `tbot keypair create` must be embedded in the
    # token spec. tbot presents its private key at join time; Teleport verifies
    # it against this registered public key — no registration secret needed.
    if [[ -z "$EXTRA_ARG" ]]; then
      echo "ERROR: bound_keypair requires the public key as the 5th argument" >&2
      exit 1
    fi
    cat <<EOF
kind: token
version: v2
metadata:
  name: ${TOKEN_NAME}
spec:
  roles: [Bot]
  join_method: bound_keypair
  bot_name: ${BOT_NAME}
  bound_keypair:
    onboarding:
      initial_public_key: "${EXTRA_ARG}"
    recovery:
      mode: "insecure"
      limit: 0
EOF
    ;;

  *)
    echo "ERROR: Unknown join_method '$JOIN_METHOD'. Use: eks | gcp | aks | kubernetes | token | bound_keypair" >&2
    exit 1
    ;;
esac
