name: Require README presence

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

jobs:
  readme-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Verify README exists in PR
        env:
          ROOTS: "use-cases proof-of-concepts templates integrations docs"
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          BASE_REF: ${{ github.base_ref }}
        run: bash tools/require-readme.sh

