name: terraform-templates

on:
  push:
    paths:
      - "templates/teleport-terraform/**"
      - ".github/workflows/terraform-templates.yml"
  pull_request:
    paths:
      - "templates/teleport-terraform/**"
      - ".github/workflows/terraform-templates.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Validate templates
        run: templates/teleport-terraform/tools/terraform-templates-check.sh
